language: csharp
solution: Kvasir.sln
dotnet: 6.0.302
env:
  global:
    - AUTHOR=$(git show -s --pretty=format:"%cn")
    - EMAIL=$(git show -s --pretty=format:"%ce")
    - MESSAGE=$(git show -s --pretty=format:"%s")
  jobs:
    - CONFIGURATION=Debug
    - CONFIGURATION=Release
branches:
  only:
    - master
install:
  - nuget restore Kvasir.sln
  - dotnet tool install coveralls.net --version 4.0.0 --tool-path coverage_tools/
script:
  - dotnet test -c $CONFIGURATION -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
  - ./coverage_tools/csmacnz.Coveralls
      --opencover
      -i ./test/UnitTests/coverage.opencover.xml
      --commitId $TRAVIS_COMMIT
      --commitBranch $TRAVIS_BRANCH
      --commitAuthor "$AUTHOR"
      --commitEmail "$EMAIL"
      --commitMessage "$MESSAGE"
      --jobId $TRAVIS_JOB_ID
      --serviceName travis-ci
      --useRelativePaths
notifications:
  email: false