# Full Appveyor.yml Reference Page: https://www.appveyor.com/docs/appveyor-yml/

version: 0.1.0+{build}
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2022
platform:
  - Any CPU
configuration:
  - Debug
  - Release
before_build:
  - nuget restore Kvasir.sln
build:
  parallel: true
  project: Kvasir.sln
  verbosity: minimal