name: Ubuntu

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  CI:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.401
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build Project(s)
        run: dotnet build -c ${{ matrix.configuration }} --no-restore
      - name: Run Unit Tests
        run: dotnet test --no-build  -c ${{ matrix.configuration }} -p:CollectCoverage=true -p:CoverletOutputFormat=lcov
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./test/UnitTests/coverage.info
          flag-name: ${{ matrix.configuration }}
          parallel: true
  Finish:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Complete Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
