name: Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  CI:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.401
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build Project(s)
        run: dotnet build -c ${{ matrix.configuration }} --no-restore
      - name: Run Unit Tests
        run: dotnet test --no-build  -c ${{ matrix.configuration }}
